from datetime import timedelta
from typing import overload

"""
This module defines custom units for electricity pricing optimization,
including Watt, WattHour, Euro, and EuroPerWh.
Each unit class supports arithmetic operations and comparisons, allowing
for intuitive calculations in the optimization process.
"""


class Watt:
    """
    Represents a unit of power in watts.

    This class supports arithmetic operations and comparisons, allowing
    for intuitive calculations involving power values.
    """
    value: float
    def __init__(self, value: float) -> None: ...

    @overload
    def __mul__(self, other: timedelta) -> WattHour: ...
    @overload
    def __mul__(self, other: float) -> Watt: ...

    @overload
    def __rmul__(self, other: timedelta) -> WattHour: ...
    @overload
    def __rmul__(self, other: float) -> Watt: ...

    @overload
    def __truediv__(self, other: float) -> Watt: ...
    @overload
    def __truediv__(self, other: Watt) -> float: ...

    def __add__(self, other: Watt) -> Watt: ...
    def __sub__(self, other: Watt) -> Watt: ...
    def __repr__(self) -> str: ...
    def get_value(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Watt) -> bool: ...
    def __le__(self, other: Watt) -> bool: ...
    def __gt__(self, other: Watt) -> bool: ...
    def __ge__(self, other: Watt) -> bool: ...
    def __neg__(self) -> Watt: ...


class WattHour:
    """
    Represents a unit of energy in watt-hours.

    This class supports arithmetic operations and comparisons, allowing
    for intuitive calculations involving energy values.
    """
    value: float
    def __init__(self, value: float) -> None: ...

    @overload
    def __mul__(self, other: EuroPerWh) -> Euro: ...
    @overload
    def __mul__(self, other: float) -> WattHour: ...

    @overload
    def __rmul__(self, other: EuroPerWh) -> Euro: ...
    @overload
    def __rmul__(self, other: float) -> WattHour: ...

    @overload
    def __truediv__(self, other: timedelta) -> Watt: ...
    @overload
    def __truediv__(self, other: float) -> WattHour: ...
    @overload
    def __truediv__(self, other: WattHour) -> float: ...
    @overload
    def __truediv__(self, other: Watt) -> timedelta: ...

    def __add__(self, other: WattHour) -> WattHour: ...
    def __sub__(self, other: WattHour) -> WattHour: ...
    def __repr__(self) -> str: ...
    def get_value(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: WattHour) -> bool: ...
    def __le__(self, other: WattHour) -> bool: ...
    def __gt__(self, other: WattHour) -> bool: ...
    def __ge__(self, other: WattHour) -> bool: ...
    def __neg__(self) -> WattHour: ...


class Euro:
    """
    Represents a monetary value in euros.

    This class supports arithmetic operations and comparisons, allowing
    for intuitive calculations involving monetary values.
    """
    value: float
    def __init__(self, value: float) -> None: ...

    def __mul__(self, other: float) -> Euro: ...
    def __rmul__(self, other: float) -> Euro: ...

    @overload
    def __truediv__(self, other: WattHour) -> EuroPerWh: ...
    @overload
    def __truediv__(self, other: float) -> Euro: ...
    @overload
    def __truediv__(self, other: Euro) -> float: ...

    def __add__(self, other: Euro) -> Euro: ...
    def __sub__(self, other: Euro) -> Euro: ...
    def __repr__(self) -> str: ...
    def get_value(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Euro) -> bool: ...
    def __le__(self, other: Euro) -> bool: ...
    def __gt__(self, other: Euro) -> bool: ...
    def __ge__(self, other: Euro) -> bool: ...
    def __neg__(self) -> Euro: ...


class EuroPerWh:
    """
    Represents a unit of cost per watt-hour in euros.

    This class supports arithmetic operations and comparisons, allowing
    for intuitive calculations involving cost per energy unit.
    """
    value: float
    def __init__(self, value: float) -> None: ...

    @overload
    def __mul__(self, other: WattHour) -> Euro: ...
    @overload
    def __mul__(self, other: float) -> EuroPerWh: ...

    @overload
    def __rmul__(self, other: WattHour) -> Euro: ...
    @overload
    def __rmul__(self, other: float) -> EuroPerWh: ...

    @overload
    def __truediv__(self, other: float) -> EuroPerWh: ...
    @overload
    def __truediv__(self, other: EuroPerWh) -> float: ...

    def __add__(self, other: EuroPerWh) -> EuroPerWh: ...
    def __sub__(self, other: EuroPerWh) -> EuroPerWh: ...
    def __repr__(self) -> str: ...
    def get_value(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: EuroPerWh) -> bool: ...
    def __le__(self, other: EuroPerWh) -> bool: ...
    def __gt__(self, other: EuroPerWh) -> bool: ...
    def __ge__(self, other: EuroPerWh) -> bool: ...
    def __neg__(self) -> EuroPerWh: ...
