//! # Prognoses Module
//!
//! This module defines the `Prognoses` struct, which is a generic container for
//! time-series data, such as electricity prices, generation, or consumption,
//! indexed by `Time`.

use std::{
    fmt::Debug,
    ops::{Add, AddAssign},
};

use crate::{
    optimizer_context::action::constant::AssignedConstantAction,
    time::{STEPS_PER_DAY, Time},
};

// const MINUTES_PER_DAY: usize = 24 * 60;

/// Holds prognoses data for each timestep in a day.
/// For example, electricity prices, generated electricity, or beyond control consumption.
#[derive(Clone, Debug)]
pub struct Prognoses<T: Clone> {
    /// Data for each timestep in a day.
    data: [T; STEPS_PER_DAY as usize],
}

impl<T: Clone> Prognoses<T> {
    pub fn new(data: [T; STEPS_PER_DAY as usize]) -> Self {
        Self { data }
    }

    pub fn get(&self, time: Time) -> Option<&T> {
        self.data.get(time.to_timestep() as usize)
    }

    /// Sets the value at the given time.
    ///
    /// # Arguments
    /// * `time` - The time at which to set the value.
    /// * `value` - The value to set.
    /// # Notes
    /// If the time is out of bounds, the function does nothing.
    pub fn set(&mut self, time: Time, value: T) {
        if time.to_timestep() < STEPS_PER_DAY {
            self.data[time.to_timestep() as usize] = value;
        }
    }

    /// Returns a reference to the internal data array.
    pub fn get_data(&self) -> &[T; STEPS_PER_DAY as usize] {
        &self.data
    }
}

impl<T: Debug + Clone> Prognoses<T> {
    /// Creates a Prognoses instance from a closure that generates values for each timestep.
    ///
    /// # Arguments
    /// * `f` - A closure that takes a timestep index and returns a value of type T.
    /// # Returns
    /// * A Prognoses instance with data generated by the closure.
    pub fn from_closure<F: Fn(Time) -> T>(f: F) -> Self {
        let data = std::array::from_fn(|t| f(Time::from_timestep(t as u32)));
        Self { data }
    }
}
impl<T: Debug + Clone + Default> Prognoses<T> {
    // same but can return Result<T, E>
    pub fn from_closure_result<F: Fn(Time) -> Result<T, E>, E>(f: F) -> Result<Self, E> {
        let mut data: [T; STEPS_PER_DAY as usize] = std::array::from_fn(|_| T::default());
        for t in 0..STEPS_PER_DAY as usize {
            data[t] = f(Time::from_timestep(t as u32))?;
        }
        Ok(Self { data })
    }
}

impl<T: From<i64> + Add<T, Output = T> + Clone> Prognoses<T> {
    /// Adds the consumption of a constant action to the prognoses data.
    /// Used to update consumption prognoses when scheduling constant actions.
    ///
    /// # Arguments
    /// * `action` - The assigned constant action to add.
    pub fn add_constant_action(&mut self, action: &AssignedConstantAction) {
        let start = action.get_start_time().to_timestep() as usize;
        let end = action.get_end_time().to_timestep() as usize;
        let consumption = action.get_action().get_consumption();

        for t in start..end {
            self.data[t] = self.data[t].clone() + T::from(consumption);
        }
    }
}

impl<T> Add for Prognoses<T>
where
    T: Add<T, Output = T> + Clone,
{
    type Output = Prognoses<T>;

    fn add(self, other: Prognoses<T>) -> Prognoses<T> {
        let mut result_data: [T; STEPS_PER_DAY as usize] =
            std::array::from_fn(|_| self.data[0].clone());
        for t in 0..STEPS_PER_DAY as usize {
            result_data[t] = self.data[t].clone() + other.data[t].clone();
        }
        Prognoses { data: result_data }
    }
}

impl<T> AddAssign for Prognoses<T>
where
    T: Add<T, Output = T> + Clone,
{
    fn add_assign(&mut self, other: Prognoses<T>) {
        for t in 0..STEPS_PER_DAY as usize {
            self.data[t] = self.data[t].clone() + other.data[t].clone();
        }
    }
}
#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use super::*;
    use crate::{optimizer_context::action::constant::ConstantAction, time::Time};

    #[test]
    fn test_new_and_get() {
        // Create an array with a specific value at one index
        let mut raw_data: [i32; STEPS_PER_DAY as usize] = [0; STEPS_PER_DAY as usize];
        raw_data[10] = 42;

        let prog = Prognoses::new(raw_data);

        // Ensure getting the value via Time works
        let time = Time::from_timestep(10);
        assert_eq!(prog.get(time), Some(&42));

        // Ensure out-of-bounds (if theoretically possible via Time) returns None or is handled
        // Note: Time::from_timestep can create values larger than STEPS_PER_DAY
        let late_time = Time::from_timestep(STEPS_PER_DAY + 1);
        assert_eq!(prog.get(late_time), None);
    }

    #[test]
    fn test_set_value() {
        let mut prog = Prognoses::new([0.0; STEPS_PER_DAY as usize]);
        let time = Time::new(12, 0); // Noon

        prog.set(time, 100.5);
        assert_eq!(*prog.get(time).unwrap(), 100.5);
    }

    #[test]
    fn test_from_closure() {
        // Generate values based on the minute count
        let prog = Prognoses::from_closure(|t| t.get_minutes() as f64);

        let t1 = Time::from_timestep(0);
        let t2 = Time::from_timestep(1);

        assert_eq!(*prog.get(t1).unwrap(), 0.0);
        assert_eq!(
            *prog.get(t2).unwrap(),
            crate::time::MINUTES_PER_TIMESTEP as f64
        );
    }

    #[test]
    fn test_from_closure_result() {
        let prog_res: Result<Prognoses<i32>, &str> = Prognoses::from_closure_result(|t| {
            if t.to_timestep() < STEPS_PER_DAY {
                Ok(1)
            } else {
                Err("Too late")
            }
        });

        assert!(prog_res.is_ok());
        assert_eq!(*prog_res.unwrap().get(Time::from_timestep(0)).unwrap(), 1);
    }

    #[test]
    fn test_add_constant_action() {
        let mut prog = Prognoses::new([0i64; STEPS_PER_DAY as usize]);
        let action = ConstantAction::new(
            Time::from_timestep(5),
            Time::from_timestep(10),
            Time::from_timestep(2),
            30,
            1,
        );
        let assigned_action = AssignedConstantAction::new(Arc::new(action), Time::from_timestep(5));
        prog.add_constant_action(&assigned_action);

        for t in 5..7 {
            assert_eq!(*prog.get(Time::from_timestep(t)).unwrap(), 30);
        }
        for t in 7..10 {
            assert_eq!(*prog.get(Time::from_timestep(t)).unwrap(), 0);
        }
    }

    #[test]
    fn test_prognoses_addition() {
        let p1 = Prognoses::new([10; STEPS_PER_DAY as usize]);
        let p2 = Prognoses::new([20; STEPS_PER_DAY as usize]);

        let sum = p1 + p2;
        assert_eq!(*sum.get(Time::from_timestep(0)).unwrap(), 30);
    }

    #[test]
    fn test_add_assign() {
        let mut p1 = Prognoses::new([10; STEPS_PER_DAY as usize]);
        let p2 = Prognoses::new([5; STEPS_PER_DAY as usize]);

        p1 += p2;
        assert_eq!(*p1.get(Time::from_timestep(0)).unwrap(), 15);
    }
}
